import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import Sidebar from "./components/layout/SideBar";
import NavBarForAdmin from "./components/layout/NavBarForAdmin";
import ProfileCreationLayer from "../(auth)/components/dashboard/ProfileCreationLayer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
      >
        <ProfileCreationLayer>
          <div className="flex h-screen overflow-hidden">
            {/* Sidebar */}
            <div className="w-64 shrink-0 z-50">
              <Sidebar />
            </div>

            {/* Main Area */}
            <div className="flex flex-col flex-1 overflow-auto">
              {/* Top Navbar */}
              <NavBarForAdmin />

              {/* Page content */}
              <main className="p-6 overflow-y-auto h-full mt-14">
                {children}
              </main>
            </div>
          </div>
        </ProfileCreationLayer>
      </body>
    </html>
  );
}
