import { educationIcon, sparkleIcon } from "./iconsProvider";
export const conditionStyleHeader = {
  line: false,
  span1: false,
};
export const template_2_styles = {
  full_Name_Style: "fullName_temp_2",
  jobTitle: "jobTitle_temp_2",
  contact_ul: "contact_ul",
  contact_li: "contact_li",
  summary_heading: "summary_heading",
  summary_text: "summary_text",
  publication_h3: "publication_h3 underline",
  experienceHeading_temp_2: "experienceHeading_temp_2 underline",
  achievement_div: "achievement_div",
  achievement_h2: "achievement_h2",
  achievement_h1: "achievement_h1",
  achievement_save_btn: "achievement-save-btn",
  achievement_delete_btn: "achievement-delete-btn",
  skill_heading: "skill_heading underline",
  skill_ul: "skill_ul",
  skill_li: "skill_li",
  skill_New: "skill_New",
  skill_input: "skill_input",
  publication_div: "publication_div",
  publication_h2: "publication_h2",
  publication_h2_1: "publication_h2_1",
  publication_new_input: "publication_new_input",
  publication_delete: "publication_delete",
  publication_delete1: "publication_delete1 ",
  publication_line: "publication_line",
  publication_date: "publication_date",
  publication_ul: "publication_ul",
  publication_li: "publication_li",
  publication_div_input: "publication_div_input",
  project_h3: "publication_h3 underline",
  project_div: "publication_div",
  project_h2: "publication_h2",
  project_h2_1: "publication_h2_1",
  project_new_input: "publication_new_input",
  project_delete: "publication_delete",
  project_delete1: "publication_delete1 ",
  project_line: "publication_line",
  project_date: "publication_date",
  project_ul: "publication_ul",
  project_li: "publication_li",
  project_div_input: "publication_div_input",
  certification_h3: "publication_h3 underline",
  certification_div: "publication_div",
  certification_h1: "achievement_h1",
  certification_h2_1: "publication_h2_1",
  certification_date: "publication_date",
  certification_ul: "publication_ul",
  certification_li: "publication_li",
  certification_line: "publication_line",
  certification_delete1: "publication_delete1",
  certification_delete: "publication_delete",
  certification_div_input: "publication_div_input",
  certification_new_input: "publication_new_input",
  training_h3: "publication_h3 underline",
  training_div: "publication_div",
  training_h1: "achievement_h1",
  training_h2: "publication_h2",
  training_h2_1: "publication_h2_1",
  training_date: "publication_date",
  training_ul: "publication_ul",
  training_li: "publication_li",
  training_line: "publication_line",
  training_delete1: "publication_delete1",
  training_delete: "publication_delete",
  training_div_input: "publication_div_input",
  training_new_input: "publication_new_input",
  interest_h3: "publication_h3 underline",
  interest_div: "publication_div",
  interest_h1: "achievement_h1",
  interest_h2: "publication_h2",
  interest_h2_1: "publication_h2_1",
  interest_date: "publication_date",
  interest_ul: "publication_ul",
  interest_li: "publication_li",
  interest_line: "publication_line",
  interest_delete1: "publication_delete1 parent",
  interest_delete: "publication_delete hidden",
  interest_div_input: "publication_div_input",
  interest_new_input: "publication_new_input",
  award_h3: "publication_h3 underline",
  award_div: "publication_div",
  award_h1: "achievement_h1",
  award_h2: "publication_h2",
  award_h2_1: "publication_h2_1",
  award_date: "publication_date",
  award_ul: "publication_ul",
  award_li: "publication_li",
  award_line: "publication_line",
  award_delete1: "publication_delete1",
  award_delete: "publication_delete",
  award_div_input: "publication_div_input",
  award_new_input: "publication_new_input",
  reference_h3: "publication_h3 underline",
  reference_ul: "reference_ul gap-3",
  reference_li: "reference_li bg-gray-300 rounded-md",
  reference_div: "  p-2 ",
  reference_h1: "achievement_h1",
  reference_h2: "publication_h2",
  reference_h2_1: "publication_h2_1",
  reference_date: "publication_date",
  reference_line: "publication_line",
  reference_delete1: "publication_delete1",
  reference_delete: "publication_delete",
  reference_div_input: "publication_div_input",
  reference_new_input: "publication_new_input",
  language_h3: "publication_h3 underline",
  language_ul: "reference_ul gap-3",
  language_li: "reference_li bg-gray-300 rounded-md ",
  language_div: "language_div p-2 ",
  language_h1: "achievement_h1",
  language_h2_1: "publication_h2_1",
  language_date: "publication_date",
  education_h3: "education_h3 underline",
  education_ul: "education_ul",
  education_div: "education_div bg-gray-300",
  education_li: "education_li",
  education_delete: "education_delete",
  education_li_2: "education_li_2",
  education_li_italic: "education_li_italic",
  education_li_date: "education_li_date",
  span1: "span1",
  span2: "span2",
};
export const template_4_styles = {
  language_ul: "flex flex-col flex-wrap pl-0 ",
  language_h3: "publication_h3",
  language_li:
    "m-2 xs:m-0 relative border-transparent border-2 hover:border-dashed hover:border-gray-500 ",
  language_div:
    "flex justify-between items-center border-2 border-transparent md:w-full hover:cursor-move ",
  language_h1:
    "flex text-[14px] xs:text-[12px] md:text-xs font-bold leading-8 hover:shadow-md hover:cursor-text hover:bg-gray-500",
  language_h2_1:
    "flex flex-wrap gap-1 text-[10px] font-semibold leading-relaxed hover:cursor-default",
  language_date: "hover:shadow-md hover:bg-gray-500",
  interest_h3: "publication_h3",
  interest_div:
    "flex justify-between items-center md:w-full hover:cursor-move border-2 border-transparent hover:border-dashed hover:border-gray-500 ",
  interest_h1:
    "flex text-base font-bold leading-8 hover:shadow-md hover:cursor-text hover:bg-gray-500",
  interest_h2:
    "text-xs xs:text-[12px] md:text-xs font-bold leading-8 hover:shadow-md hover:cursor-text hover:bg-gray-500",
  interest_h2_1:
    "flex flex-wrap gap-1 text-[10px] font-semibold leading-relaxed hover:cursor-default",
  interest_date: "hover:shadow-md hover:bg-gray-500",
  interest_ul: "flex flex-col flex-wrap pl-0 text-xs xs:text-[12px] md:text-xs",
  interest_li:
    "m-2 xs:m-0 relative hover:shadow-md hover:cursor-move      hover:bg-gray-500",
  interest_line: "publication_line",
  interest_delete1:
    "hover:shadow-md hover:cursor-move  hover:bg-gray-500 relative list-disc w-auto parent",
  interest_delete: "publication_delete hidden",
  interest_div_input: "publication_div_input",
  interest_new_input: "publication_new_input",
  full_Name_Style:
    "text-4xl font-bold border-2 border-transparent hover:border-dashed hover:border-gray-500 xs:text-2xl md:4xl lg:text-4xl hover:shadow-md hover:bg-gray-100",
  jobTitle:
    "text-lg border-2 border-transparent xs:text-xs md:text-2xl lg:text-2xl hover:shadow-md hover:bg-gray-100 hover:border-dashed hover:border-gray-500",
  skill_heading:
    "flex flex-row items-center gap-2 mb-2 -mr-6 text-base font-semibold uppercase border-2 border-transparent md:-mr-6 md:text-md hover:border-dashed hover:border-gray-500 hover:w-full",
  skill_ul:
    "border-2 border-transparent hover:border-dashed hover:border-gray-500 px-4 flex flex-col  gap-3 mb-4 text-xs xs:text-[12px] md:text-xs",
  skill_li:
    "hover:shadow-md hover:cursor-move  hover:border-[1px] hover:border-dashed     hover:bg-gray-500",
  skill_New: "skill_New",
  span1: "span1",
  span2: "span2",
  skill_input: "skill_input",
  conatact_heading:
    "flex flex-row items-center gap-2 mb-2 -mr-6 text-base font-semibold uppercase border-2 border-transparent md:-mr-6 md:mt-4 hover:border-dashed hover:border-gray-500 hover:w-full",
  contact_ul: "flex flex-col gap-2 pl-0 mb-4 text-xs break-all",
  contact_li:
    "hover:shadow-md mb-[8px] hover:bg-gray-500  flex flex-row gap-2  justify-start items-center",
  training_h3: "publication_h3",
  training_div: "publication_div",
  training_h1: "achievement_h1",
  training_h2: "publication_h2",
  training_h2_1: "publication_h2_1",
  training_date: "publication_date",
  training_ul: "publication_ul",
  training_li: "publication_li",
  training_line: "publication_line",
  training_delete1: "publication_delete1",
  training_delete: "publication_delete",
  training_div_input: "publication_div_input",
  training_new_input: "publication_new_input",
  certification_h3: "publication_h3",
  certification_div: "publication_div",
  certification_h1: "achievement_h1",
  certification_h2_1: "publication_h2_1",
  certification_date: "publication_date",
  certification_ul: "publication_ul",
  certification_li: "publication_li",
  certification_line: "publication_line",
  certification_delete1: "publication_delete1",
  certification_delete: "publication_delete",
  certification_div_input: "publication_div_input",
  certification_new_input: "publication_new_input",
  experienceHeading_temp_2: "experienceHeading_temp_2",
  summary_heading: "summary_heading",
  summary_text: "summary_text",
  publication_h3: "publication_h3",
  achievement_div: "achievement_div",
  achievement_h2: "achievement_h2",
  achievement_h1: "achievement_h1",
  achievement_save_btn: "achievement-save-btn",
  achievement_delete_btn: "achievement-delete-btn",
  education_h3: "education_h3",
  education_ul: "grid grid-cols-2 gap-2 xs:grid-cols-2 md:grid-cols-2 !mt-4",
  education_div: "education_div",
  education_li: "education_li",
  education_delete: "education_delete",
  education_li_2: "education_li_2",
  education_li_italic: "education_li_italic",
  education_li_date: "education_li_date",
  publication_div: "publication_div",
  publication_h2: "publication_h2",
  publication_h2_1: "publication_h2_1",
  publication_new_input: "publication_new_input",
  publication_delete: "publication_delete",
  publication_delete1: "publication_delete1 ",
  publication_line: "publication_line",
  publication_date: "publication_date",
  publication_ul: "publication_ul",
  publication_li: "publication_li",
  publication_div_input: "publication_div_input",
  project_h3: "publication_h3",
  project_div: "publication_div",
  project_h2: "publication_h2",
  project_h2_1: "publication_h2_1",
  project_new_input: "publication_new_input",
  project_delete: "publication_delete",
  project_delete1: "publication_delete1 ",
  project_line: "publication_line",
  project_date: "publication_date",
  project_ul: "publication_ul",
  project_li: "publication_li",
  project_div_input: "publication_div_input",
  award_h3: "publication_h3",
  award_div: "publication_div",
  award_h1: "achievement_h1",
  award_h2: "publication_h2",
  award_h2_1: "publication_h2_1",
  award_date: "publication_date",
  award_ul: "publication_ul",
  award_li: "publication_li",
  award_line: "publication_line",
  award_delete1: "publication_delete1",
  award_delete: "publication_delete",
  award_div_input: "publication_div_input",
  award_new_input: "publication_new_input",
  reference_h3: "publication_h3",
  reference_ul: "reference_ul",
  reference_li: "reference_li",
  reference_div: "publication_div",
  reference_h1: "achievement_h1",
  reference_h2: "publication_h2",
  reference_h2_1: "publication_h2_1",
  reference_date: "publication_date",
  reference_line: "publication_line",
  reference_delete1: "publication_delete1",
  reference_delete: "publication_delete",
  reference_div_input: "publication_div_input",
  reference_new_input: "publication_new_input",
};
export const template_6_styles = {
  full_Name_Style:
    "text-4xl font-bold border-2 border-transparent xs:text-2xl md:4xl lg:text-4xl hover:shadow-md hover:bg-gray-100 hover:border-dashed hover:border-gray-500     ",
  jobTitle:
    "w-full text-lg border-2 border-transparent xs:text-xs md:text-2xl lg:text-2xl xs:leading-none hover:shadow-md hover:bg-gray-100 hover:border-dashed hover:border-gray-500",
  conatact_heading:
    "flex flex-row items-center gap-2 mb-2 -mr-6 text-base font-semibold uppercase border-2 border-transparent md:-mr-6 md:mt-4 hover:border-dashed hover:border-gray-500 hover:w-full",
  contact_ul:
    "flex  flex-col xs:flex-col justify-between  pl-0 my-2 text-xs break-all md:flex-row",
  contact_li:
    "hover:shadow-md hover:bg-gray-100 text-xs   flex flex-row gap-1  items-center justify-start md:w-[20%] xs:w-full ",
  skill_heading:
    "flex flex-row flex-wrap items-center gap-2 my-1 text-base font-semibold uppercase border-2 border-transparent hover:border-dashed hover:border-gray-500",
  skill_ul:
    "border-2 border-transparent hover:border-dashed hover:border-gray-500 px-4 gap-1 flex flex-wrap h-[20%] text-xs",
  skill_li:
    "hover:shadow-md  w-[32%]  sm:w-[32%]  hover:cursor-move parent hover:border-dashed mr-2 hover:border-gray-500 hover:border  hover:bg-gray-100 border-transparent border-[1px]",
  training_h3: "publication_h3",
  training_div: "publication_div",
  training_h1: "achievement_h1",
  training_h2: "publication_h2",
  training_h2_1: "publication_h2_1",
  training_date: "publication_date",
  training_ul: "publication_ul",
  training_li: "publication_li",
  training_line: "publication_line",
  training_delete1: "publication_delete1",
  training_delete: "publication_delete",
  training_div_input: "publication_div_input",
  training_new_input: "publication_new_input",
  certification_h3: "publication_h3",
  certification_div: "publication_div",
  certification_h1: "achievement_h1",
  certification_h2_1: "publication_h2_1",
  certification_date: "publication_date",
  certification_ul: "publication_ul",
  certification_li: "publication_li",
  certification_line: "publication_line",
  certification_delete1: "publication_delete1",
  certification_delete: "publication_delete",
  certification_div_input: "publication_div_input",
  certification_new_input: "publication_new_input",
  experienceHeading_temp_2: "experienceHeading_temp_2",
  summary_heading: "summary_heading",
  summary_text: "summary_text",
  publication_h3: "publication_h3",
  achievement_div: "achievement_div",
  achievement_h2: "achievement_h2",
  achievement_h1: "achievement_h1",
  achievement_save_btn: "achievement-save-btn",
  achievement_delete_btn: "achievement-delete-btn",
  education_h3: "education_h3",
  education_ul: "education_ul",
  education_div: "education_div",
  education_li: "education_li",
  education_delete: "education_delete",
  education_li_2: "education_li_2",
  education_li_italic: "education_li_italic",
  education_li_date: "education_li_date",
  publication_div: "publication_div",
  publication_h2: "publication_h2",
  publication_h2_1: "publication_h2_1",
  publication_new_input: "publication_new_input",
  publication_delete: "publication_delete",
  publication_delete1: "publication_delete1 ",
  publication_line: "publication_line",
  publication_date: "publication_date",
  publication_ul: "publication_ul",
  publication_li: "publication_li",
  publication_div_input: "publication_div_input",
  project_h3: "publication_h3",
  project_div: "publication_div",
  project_h2: "publication_h2",
  project_h2_1: "publication_h2_1",
  project_new_input: "publication_new_input",
  project_delete: "publication_delete",
  project_delete1: "publication_delete1 ",
  project_line: "publication_line",
  project_date: "publication_date",
  project_ul: "publication_ul",
  project_li: "publication_li",
  project_div_input: "publication_div_input",
  interest_h3: "publication_h3",
  interest_div: "publication_div",
  interest_h1: "achievement_h1",
  interest_h2: "publication_h2",
  interest_h2_1: "publication_h2_1",
  interest_date: "publication_date",
  interest_ul: "publication_ul",
  interest_li: "publication_li",
  interest_line: "publication_line",
  interest_delete1: "publication_delete1 parent",
  interest_delete: "publication_delete hidden",
  interest_div_input: "publication_div_input",
  interest_new_input: "publication_new_input",
  award_h3: "publication_h3",
  award_div: "publication_div",
  award_h1: "achievement_h1",
  award_h2: "publication_h2",
  award_h2_1: "publication_h2_1",
  award_date: "publication_date",
  award_ul: "publication_ul",
  award_li: "publication_li",
  award_line: "publication_line",
  award_delete1: "publication_delete1",
  award_delete: "publication_delete",
  award_div_input: "publication_div_input",
  award_new_input: "publication_new_input",
  reference_h3: "publication_h3",
  reference_ul: "reference_ul",
  reference_li: "reference_li",
  reference_div: "p-2",
  reference_h1: "achievement_h1",
  reference_h2: "publication_h2",
  reference_h2_1: "publication_h2_1",
  reference_date: "publication_date",
  reference_line: "publication_line",
  reference_delete1: "publication_delete1",
  reference_delete: "publication_delete",
  reference_div_input: "publication_div_input",
  reference_new_input: "publication_new_input",
  language_h3: "publication_h3",
  language_ul: "reference_ul",
  language_li: "reference_li",
  language_div: "language_div ",
  language_h1: "achievement_h1",
  language_h2_1: "publication_h2_1",
  language_date: "publication_date",
  span1: "span1",
  span2: "span2",
};
export const template_8_styles = {
  full_Name_Style:
    "text-4xl font-bold border-2 border-transparent xs:text-2xl md:4xl lg:text-4xl hover:shadow-md hover:bg-gray-100 hover:border-dashed hover:border-gray-500 ",
  jobTitle:
    "text-lg border-2 border-transparent xs:text-xs md:text-2xl lg:text-2xl hover:shadow-md hover:bg-gray-100 hover:border-dashed hover:border-gray-500",
  conatact_heading:
    "flex flex-row items-center gap-2 mb-2 -mr-6 text-base font-semibold uppercase border-2 border-transparent md:-mr-6 md:mt-4 hover:border-dashed hover:border-gray-500 hover:w-full",
  contact_ul:
    "flex flex-col justify-between w-full gap-3 pl-0 mt-8 mb-4 text-xs break-all md:flex-col",
  contact_li:
    "flex flex-row items-start justify-start gap-1 hover:shadow-md hover:bg-gray-100",
  skill_heading:
    "flex items-center my-1 justify-center gap-2  text-base font-semibold uppercase wl-full border-2 border-transparent hover:border-dashed hover:border-gray-500 ",
  skill_ul:
    "border-2 border-transparent hover:border-dashed hover:border-gray-500  px-4 flex  flex-wrap gap-1 h-[20%] gap-4 mx-2 text-xs",
  skill_li:
    "hover:shadow-md w-[30%] xs:w-[45%] xs:pr-4 md:w-[30%] hover:cursor-move parent hover:border-dashed hover:border-gray-500 hover:border  hover:bg-gray-100 border-transparent border-[1px]",
  training_h3: "publication_h3",
  training_div: "publication_div",
  training_h1: "achievement_h1",
  training_h2: "publication_h2",
  training_h2_1: "publication_h2_1",
  training_date: "publication_date",
  training_ul: "publication_ul",
  training_li: "publication_li",
  training_line: "publication_line",
  training_delete1: "publication_delete1",
  training_delete: "publication_delete",
  training_div_input: "publication_div_input",
  training_new_input: "publication_new_input",
  certification_h3: "publication_h3",
  certification_div: "publication_div",
  certification_h1: "achievement_h1",
  certification_h2_1: "publication_h2_1",
  certification_date: "publication_date",
  certification_ul: "publication_ul",
  certification_li: "publication_li",
  certification_line: "publication_line",
  certification_delete1: "publication_delete1",
  certification_delete: "publication_delete",
  certification_div_input: "publication_div_input",
  certification_new_input: "publication_new_input",
  experienceHeading_temp_2: "experienceHeading_temp_2",
  summary_heading: "summary_heading",
  summary_text: "summary_text",
  publication_h3: "publication_h3",
  achievement_div: "achievement_div",
  achievement_h2: "achievement_h2",
  achievement_h1: "achievement_h1",
  achievement_save_btn: "achievement-save-btn",
  achievement_delete_btn: "achievement-delete-btn",
  education_h3: "education_h3",
  education_ul: "education_ul",
  education_div: "education_div",
  education_li: "education_li",
  education_delete: "education_delete",
  education_li_2: "education_li_2",
  education_li_italic: "education_li_italic",
  education_li_date: "education_li_date",
  publication_div: "publication_div",
  publication_h2: "publication_h2",
  publication_h2_1: "publication_h2_1",
  publication_new_input: "publication_new_input",
  publication_delete: "publication_delete",
  publication_delete1: "publication_delete1 ",
  publication_line: "publication_line",
  publication_date: "publication_date",
  publication_ul: "publication_ul",
  publication_li: "publication_li",
  publication_div_input: "publication_div_input",
  project_h3: "publication_h3",
  project_div: "publication_div",
  project_h2: "publication_h2",
  project_h2_1: "publication_h2_1",
  project_new_input: "publication_new_input",
  project_delete: "publication_delete",
  project_delete1: "publication_delete1 ",
  project_line: "publication_line",
  project_date: "publication_date",
  project_ul: "publication_ul",
  project_li: "publication_li",
  project_div_input: "publication_div_input",
  interest_h3: "publication_h3",
  interest_div: "publication_div",
  interest_h1: "achievement_h1",
  interest_h2: "publication_h2",
  interest_h2_1: "publication_h2_1",
  interest_date: "publication_date",
  interest_ul: "publication_ul",
  interest_li: "publication_li",
  interest_line: "publication_line",
  interest_delete1: "publication_delete1 parent",
  interest_delete: "publication_delete hidden",
  interest_div_input: "publication_div_input",
  interest_new_input: "publication_new_input",
  award_h3: "publication_h3",
  award_div: "publication_div",
  award_h1: "achievement_h1",
  award_h2: "publication_h2",
  award_h2_1: "publication_h2_1",
  award_date: "publication_date",
  award_ul: "publication_ul",
  award_li: "publication_li",
  award_line: "publication_line",
  award_delete1: "publication_delete1",
  award_delete: "publication_delete",
  award_div_input: "publication_div_input",
  award_new_input: "publication_new_input",
  reference_h3: "publication_h3",
  reference_ul: "reference_ul",
  reference_li: "reference_li",
  reference_div: "p-2",
  reference_h1: "achievement_h1",
  reference_h2: "publication_h2",
  reference_h2_1: "publication_h2_1",
  reference_date: "publication_date",
  reference_line: "publication_line",
  reference_delete1: "publication_delete1",
  reference_delete: "publication_delete",
  reference_div_input: "publication_div_input",
  reference_new_input: "publication_new_input",
  language_h3: "publication_h3",
  language_ul: "reference_ul",
  language_li: "reference_li",
  language_div: "language_div ",
  language_h1: "achievement_h1",
  language_h2_1: "publication_h2_1",
  language_date: "publication_date",
  span1: "span1",
  span2: "span2",
};
export const template_9_styles = {
  full_Name_Style:
    "text-4xl font-bold border-2 border-transparent xs:text-2xl md:4xl lg:text-4xl hover:shadow-md hover:bg-gray-100 hover:border-dashed hover:border-gray-500",
  jobTitle:
    "text-lg border-2 border-transparent xs:text-xs md:text-2xl lg:text-2xl hover:shadow-md hover:bg-gray-100 hover:border-dashed hover:border-gray-500",
  conatact_heading:
    "flex flex-row items-center gap-2 mb-2 -mr-6 text-base font-semibold uppercase border-2 border-transparent md:-mr-6 md:mt-4 hover:border-dashed hover:border-gray-500 hover:w-full",
  contact_ul:
    "flex flex-row xs:flex-col justify-between w-full gap-3 pl-0 text-xs break-all md:flex-row",
  contact_li:
    "md:w-[20%] xs:w-full border-2 border-transparent hover:border-dashed hover:border-gray-500   hover:shadow-md hover:bg-gray-100 text-xs flex flex-row gap-1  items-center justify-start",
  skill_heading:
    "flex items-center gap-2 my-1 text-base font-semibold uppercase border-2 border-transparent hover:border-dashed hover:border-gray-500",
  skill_ul:
    "border-2 border-transparent hover:border-dashed hover:border-gray-500  px-4  flex flex-wrap  gap-1 h-[20%]  mb-4 text-xs",
  skill_li:
    "hover:shadow-md w-[30%] xs:w-full md:w-[30%]  hover:cursor-move hover:border-dashed mx-2 hover:border-gray-500 hover:border  hover:bg-gray-100 border-transparent border-[1px]",
  training_h3: "publication_h3",
  training_div: "publication_div",
  training_h1: "achievement_h1",
  training_h2: "publication_h2",
  training_h2_1: "publication_h2_1",
  training_date: "publication_date",
  training_ul: "publication_ul",
  training_li: "publication_li",
  training_line: "publication_line",
  training_delete1: "publication_delete1",
  training_delete: "publication_delete",
  training_div_input: "publication_div_input",
  training_new_input: "publication_new_input",
  certification_h3: "publication_h3",
  certification_div: "publication_div",
  certification_h1: "achievement_h1",
  certification_h2_1: "publication_h2_1",
  certification_date: "publication_date",
  certification_ul: "publication_ul",
  certification_li: "publication_li",
  certification_line: "publication_line",
  certification_delete1: "publication_delete1",
  certification_delete: "publication_delete",
  certification_div_input: "publication_div_input",
  certification_new_input: "publication_new_input",
  experienceHeading_temp_2: "experienceHeading_temp_2",
  summary_heading: "summary_heading",
  summary_text: "summary_text",
  publication_h3: "publication_h3",
  achievement_div: "achievement_div",
  achievement_h2: "achievement_h2",
  achievement_h1: "achievement_h1",
  achievement_save_btn: "achievement-save-btn",
  achievement_delete_btn: "achievement-delete-btn",
  education_h3: "education_h3",
  education_ul: "education_ul",
  education_div: "education_div bg-gray-200 rounded-md",
  education_li: "education_li",
  education_delete: "education_delete",
  education_li_2: "education_li_2",
  education_li_italic: "education_li_italic",
  education_li_date: "education_li_date",
  publication_div: "publication_div",
  publication_h2: "publication_h2",
  publication_h2_1: "publication_h2_1",
  publication_new_input: "publication_new_input",
  publication_delete: "publication_delete",
  publication_delete1: "publication_delete1 ",
  publication_line: "publication_line",
  publication_date: "publication_date",
  publication_ul: "publication_ul",
  publication_li: "publication_li",
  publication_div_input: "publication_div_input",
  project_h3: "publication_h3",
  project_div: "publication_div",
  project_h2: "publication_h2",
  project_h2_1: "publication_h2_1",
  project_new_input: "publication_new_input",
  project_delete: "publication_delete",
  project_delete1: "publication_delete1 ",
  project_line: "publication_line",
  project_date: "publication_date",
  project_ul: "publication_ul",
  project_li: "publication_li",
  project_div_input: "publication_div_input",
  interest_h3: "publication_h3",
  interest_div: "publication_div",
  interest_h1: "achievement_h1",
  interest_h2: "publication_h2",
  interest_h2_1: "publication_h2_1",
  interest_date: "publication_date",
  interest_ul: "publication_ul",
  interest_li: "publication_li",
  interest_line: "publication_line",
  interest_delete1: "publication_delete1 parent",
  interest_delete: "publication_delete hidden",
  interest_div_input: "publication_div_input",
  interest_new_input: "publication_new_input",
  award_h3: "publication_h3",
  award_div: "publication_div",
  award_h1: "achievement_h1",
  award_h2: "publication_h2",
  award_h2_1: "publication_h2_1",
  award_date: "publication_date",
  award_ul: "publication_ul",
  award_li: "publication_li",
  award_line: "publication_line",
  award_delete1: "publication_delete1",
  award_delete: "publication_delete",
  award_div_input: "publication_div_input",
  award_new_input: "publication_new_input",
  reference_h3: "publication_h3",
  reference_ul: "reference_ul gap-1 mt-1",
  reference_li: "reference_li rounded-md bg-gray-200",
  reference_div: "p-2",
  reference_h1: "achievement_h1",
  reference_h2: "publication_h2",
  reference_h2_1: "publication_h2_1",
  reference_date: "publication_date",
  reference_line: "publication_line",
  reference_delete1: "publication_delete1",
  reference_delete: "publication_delete",
  reference_div_input: "publication_div_input",
  reference_new_input: "publication_new_input",
  language_h3: "publication_h3",
  language_ul: "reference_ul mt-1 gap-1",
  language_li: "reference_li ",
  language_div: "language_div p-2",
  language_h1: "achievement_h1",
  language_h2_1: "publication_h2_1",
  language_date: "publication_date",
  span1: "span1",
  span2: "span2",
};
export const template_10_styles = {
  bgColor:
    "rounded-3xl xs:-mx-1 md:mx-0 text-gray-100 bg-[#043382] py-2 px-6 mt-6 mb-3 xs:px-2 sm:px-2 md:px-6 lg:px-6 w-fit",
  full_Name_Style:
    "text-4xl font-bold text-gray-100 border-2 border-transparent hover:shadow-md hover:bg-gray-500 hover:border-dashed hover:border-gray-500 flex justify-center",
  jobTitle:
    "flex items-center justify-center text-lg text-gray-100 border-2 border-transparent xs:text-xs md:text-2xl lg:text-2xl hover:shadow-md hover:bg-gray-500 hover:border-dashed hover:border-gray-500",
  conatact_heading:
    "flex flex-row items-center gap-2 mb-2 -mr-6 text-base font-semibold uppercase border-2 border-transparent md:-mr-6 md:mt-4 hover:border-dashed hover:border-gray-500 hover:w-full",
  contact_ul: "flex flex-col gap-2 pl-0 mt-4 text-xs break-all",
  contact_li:
    "flex items-center hover:shadow-md mb-[8px] hover:bg-gray-500 text-xs flex-row gap-1 justify-start   hover:border-[1px] hover:border-dashed     ",
  skill_heading:
    "flex flex-row items-center gap-2 mb-0 text-base font-semibold uppercase border-2 border-transparent hover:border-dashed hover:border-gray-500",
  skill_ul:
    "flex flex-col gap-3 mb-4 text-xs border-2 px-4 border-transparent hover:border-dashed hover:border-gray-500",
  skill_li:
    "hover:shadow-md hover:cursor-move parent hover:border-[1px] hover:border-dashed     hover:bg-gray-500",
  training_h3: "publication_h3",
  training_div: "publication_div",
  training_h1: "achievement_h1",
  training_h2: "publication_h2",
  training_h2_1: "publication_h2_1",
  training_date: "publication_date",
  training_ul: "publication_ul",
  training_li: "publication_li",
  training_line: "publication_line",
  training_delete1: "publication_delete1",
  training_delete: "publication_delete",
  training_div_input: "publication_div_input",
  training_new_input: "publication_new_input",
  certification_h3: "publication_h3",
  certification_div: "publication_div",
  certification_h1: "achievement_h1",
  certification_h2_1: "publication_h2_1",
  certification_date: "publication_date",
  certification_ul: "publication_ul",
  certification_li: "publication_li",
  certification_line: "publication_line",
  certification_delete1: "publication_delete1",
  certification_delete: "publication_delete",
  certification_div_input: "publication_div_input",
  certification_new_input: "publication_new_input",
  experienceHeading_temp_2: "experienceHeading_temp_2",
  summary_heading: "summary_heading",
  summary_text: "summary_text",
  publication_h3: "publication_h3",
  achievement_div: "achievement_div",
  achievement_h2: "achievement_h2",
  achievement_h1: "achievement_h1",
  achievement_save_btn: "achievement-save-btn",
  achievement_delete_btn: "achievement-delete-btn",
  education_h3: "education_h3",
  education_ul: "grid grid-cols-2 gap-2 xs:grid-cols-2 md:grid-cols-2 !mt-4",
  education_div: "education_div p-2 mt-4 bg-gray-200 rounded-md",
  education_li: "education_li",
  education_delete: "education_delete",
  education_li_2: "education_li_2",
  education_li_italic: "education_li_italic",
  education_li_date: "education_li_date",
  publication_div: "publication_div",
  publication_h2: "publication_h2",
  publication_h2_1: "publication_h2_1",
  publication_new_input: "publication_new_input",
  publication_delete: "publication_delete",
  publication_delete1: "publication_delete1 ",
  publication_line: "publication_line",
  publication_date: "publication_date",
  publication_ul: "publication_ul",
  publication_li: "publication_li",
  publication_div_input: "publication_div_input",
  project_h3: "publication_h3",
  project_div: "publication_div",
  project_h2: "publication_h2",
  project_h2_1: "publication_h2_1",
  project_new_input: "publication_new_input",
  project_delete: "publication_delete",
  project_delete1: "publication_delete1 ",
  project_line: "publication_line",
  project_date: "publication_date",
  project_ul: "publication_ul",
  project_li: "publication_li",
  project_div_input: "publication_div_input",
  interest_h3: "publication_h3",
  interest_div:
    "flex justify-between items-center hover:border-2 hover:border-dashed hover:border-gray-500 hover:border-2 md:w-full hover:cursor-move ",
  interest_h1:
    "flex text-base font-bold leading-8 hover:shadow-md hover:cursor-text hover:bg-gray-500",
  interest_h2:
    "text-xs xs:text-[12px] md:text-xs font-bold leading-8 hover:shadow-md hover:cursor-text hover:bg-gray-500",
  interest_h2_1:
    "flex flex-wrap gap-1 text-[10px] font-semibold leading-relaxed hover:cursor-default",
  interest_date: "hover:shadow-md hover:bg-gray-500",
  interest_ul:
    "flex flex-col flex-wrap pl-0 text-xs xs:text-[12px] md:text-xs  h",
  interest_li:
    "m-2 xs:m-0 relative border-transparent border-2 hover:border-dashed hover:border-gray-500",
  interest_line: "publication_line",
  interest_delete1:
    " list-disc hover:cursor-move hover:shadow-md hover:cursor-move  hover:border-[1px] hover:border-dashed     hover:bg-gray-500 relative ",
  interest_delete: "publication_delete hidden",
  interest_div_input: "publication_div_input",
  interest_new_input: "publication_new_input",
  award_h3: "publication_h3",
  award_div: "publication_div",
  award_h1: "achievement_h1",
  award_h2: "publication_h2",
  award_h2_1: "publication_h2_1",
  award_date: "publication_date",
  award_ul: "publication_ul",
  award_li: "publication_li",
  award_line: "publication_line",
  award_delete1: "publication_delete1",
  award_delete: "publication_delete",
  award_div_input: "publication_div_input",
  award_new_input: "publication_new_input",
  reference_h3: "publication_h3",
  reference_ul: "reference_ul mt-4 gap-3",
  reference_li: "reference_li bg-gray-200 rounded-md",
  reference_div: "p-2",
  reference_h1: "achievement_h1",
  reference_h2: "publication_h2",
  reference_h2_1: "publication_h2_1",
  reference_date: "publication_date",
  reference_line: "publication_line",
  reference_delete1: "publication_delete1",
  reference_delete: "publication_delete",
  reference_div_input: "publication_div_input",
  reference_new_input: "publication_new_input",
  language_ul: "flex flex-col flex-wrap pl-0 ",
  language_h3: "publication_h3",
  language_li:
    "m-2 xs:m-0 relative border-transparent border-2 hover:border-dashed hover:border-gray-500 ",
  language_div:
    "flex justify-between items-center border-2 border-transparent md:w-full hover:cursor-move ",
  language_h1:
    "flex text-[14px] xs:text-[12px] md:text-xs font-bold leading-8 hover:shadow-md hover:cursor-text hover:bg-gray-500",
  language_h2_1:
    "flex flex-wrap gap-1 text-[10px] font-semibold leading-relaxed hover:cursor-default",
  language_date: "hover:shadow-md hover:bg-gray-500",
  span1: "span1",
  span2: "span2",
};
export const template_15_styles = {
  bgColor: "bg-[#444440] text-gray-100 py-1 px-4 flex gap-2 rounded-sm",
  full_Name_Style:
    "text-4xl font-bold text-center xs:text-4xl hover:shadow-md hover:bg-gray-100 border-2 border-transparent hover:border-dashed hover:border-gray-500",
  jobTitle:
    "my-2 text-xl leading-none text-center border-2 border-transparent hover:shadow-md hover:bg-gray-100 hover:border-dashed hover:border-gray-500",
  conatact_heading:
    "flex flex-row items-center gap-2 mb-2 -mr-6 text-base font-semibold uppercase border-2 border-transparent md:-mr-6 md:mt-4 hover:border-dashed hover:border-gray-500 hover:w-full",
  contact_ul: "flex flex-col mt-4 w-full gap-3 pl-0 mb-4 text-xs break-all",
  contact_li:
    "flex flex-row items-start justify-start gap-3 text-xs hover:shadow-md hover:bg-gray-100 hover:border-[1px] hover:border-dashed hover:border-black",
  skill_heading:
    "flex uppercase text-base xs:px-2 font-semibold text-gray-100 gap-2 items-center  py-1 rounded-sm  border-2 border-transparent hover:border-dashed hover:border-gray-500",
  skill_ul:
    "flex flex-col w-full gap-2 px-4  mb-4 text-xs border-2 border-transparent hover:border-dashed hover:border-gray-500 mt-4",
  skill_li:
    "hover:shadow-md hover:cursor-move px-0 xs:px-2 md:px-0 parent hover:border-dashed hover:border-gray-500 hover:border  hover:bg-gray-100 border-transparent border-[1px]",
  training_h3: "publication_h3",
  training_div: "publication_div",
  training_h1: "achievement_h1",
  training_h2: "publication_h2",
  training_h2_1: "publication_h2_1",
  training_date: "publication_date",
  training_ul: "publication_ul",
  training_li: "publication_li",
  training_line: "publication_line",
  training_delete1: "publication_delete1",
  training_delete: "publication_delete",
  training_div_input: "publication_div_input",
  training_new_input: "publication_new_input",
  certification_h3: "publication_h3",
  certification_div: "publication_div",
  certification_h1: "achievement_h1",
  certification_h2_1: "publication_h2_1",
  certification_date: "publication_date",
  certification_ul: "publication_ul",
  certification_li: "publication_li",
  certification_line: "publication_line",
  certification_delete1: "publication_delete1",
  certification_delete: "publication_delete",
  certification_div_input: "publication_div_input",
  certification_new_input: "publication_new_input",
  experienceHeading_temp_2: "experienceHeading_temp_2",
  summary_heading: "summary_heading",
  summary_text: "summary_text",
  publication_h3: "publication_h3 ",
  achievement_div: "achievement_div",
  achievement_h2: "achievement_h2",
  achievement_h1: "achievement_h1",
  achievement_save_btn: "achievement-save-btn",
  achievement_delete_btn: "achievement-delete-btn",
  education_h3: "education_h3",
  education_ul: "grid grid-cols-2 gap-2 xs:grid-cols-2 md:grid-cols-2 mt-4",
  education_div: "education_div bg-gray-200 rounded-md ",
  education_li: "education_li",
  education_delete: "education_delete",
  education_li_2: "education_li_2",
  education_li_italic: "education_li_italic",
  education_li_date: "education_li_date",
  publication_div: "publication_div",
  publication_h2: "publication_h2",
  publication_h2_1: "publication_h2_1",
  publication_new_input: "publication_new_input",
  publication_delete: "publication_delete",
  publication_delete1: "publication_delete1 ",
  publication_line: "publication_line",
  publication_date: "publication_date",
  publication_ul: "publication_ul",
  publication_li: "publication_li",
  publication_div_input: "publication_div_input",
  project_h3: "publication_h3",
  project_div: "publication_div",
  project_h2: "publication_h2",
  project_h2_1: "publication_h2_1",
  project_new_input: "publication_new_input",
  project_delete: "publication_delete",
  project_delete1: "publication_delete1 ",
  project_line: "publication_line",
  project_date: "publication_date",
  project_ul: "publication_ul",
  project_li: "publication_li",
  project_div_input: "publication_div_input",
  interest_h3:
    "flex uppercase text-base xs:px-2 font-semibold text-gray-100 gap-2 items-center  py-1 rounded-sm  border-2 border-transparent hover:border-dashed hover:border-gray-500",
  interest_div:
    "flex justify-between items-center border-2 border-transparent md:w-full hover:cursor-move border-2 border-transparent hover:border-dashed hover:border-gray-500",
  interest_h1:
    "flex text-base font-bold leading-8 hover:shadow-md hover:cursor-text hover:bg-gray-500",
  interest_h2:
    "text-xs xs:text-[12px] md:text-xs font-bold leading-8 hover:shadow-md hover:cursor-text hover:bg-gray-500",
  interest_h2_1:
    "flex flex-wrap gap-1 text-[10px] font-semibold leading-relaxed hover:cursor-default",
  interest_date: "hover:shadow-md hover:bg-gray-500",
  interest_ul: "flex flex-col flex-wrap pl-0 text-xs xs:text-[12px] md:text-xs",
  interest_li:
    "hover:shadow-md hover:cursor-move px-0 xs:px-2 md:px-0 parent hover:border-dashed hover:border-gray-500 hover:border  hover:bg-gray-100 border-transparent border-[1px] flex items-center gap-2 justify-between",
  interest_line: "publication_line",
  interest_delete1:
    "hover:border-dashed list-disc hover:cursor-move hover:border-gray-100 border-[1px] hover:border-[1px] border-transparent hover:shadow-md relative hover:bg-gray-100 parent",
  interest_delete: "publication_delete hidden",
  interest_div_input: "publication_div_input",
  interest_new_input: "publication_new_input",
  award_h3: "publication_h3",
  award_div: "publication_div",
  award_h1: "achievement_h1",
  award_h2: "publication_h2",
  award_h2_1: "publication_h2_1",
  award_date: "publication_date",
  award_ul: "publication_ul",
  award_li: "publication_li",
  award_line: "publication_line",
  award_delete1: "publication_delete1",
  award_delete: "publication_delete",
  award_div_input: "publication_div_input",
  award_new_input: "publication_new_input",
  reference_h3: "publication_h3",
  reference_ul: "reference_ul gap-1",
  reference_li: "reference_li bg-gray-200 rounded-md ",
  reference_div: "p-2",
  reference_h1: "achievement_h1",
  reference_h2: "publication_h2",
  reference_h2_1: "publication_h2_1",
  reference_date: "publication_date",
  reference_line: "publication_line",
  reference_delete1: "publication_delete1",
  reference_delete: "publication_delete",
  reference_div_input: "publication_div_input",
  reference_new_input: "publication_new_input",
  language_ul: "flex flex-col flex-wrap pl-0 ",
  language_h3:
    "flex uppercase text-base xs:px-2 font-semibold text-gray-100 gap-2 items-center  py-1 rounded-sm  border-2 border-transparent hover:border-dashed hover:border-gray-500",
  language_li:
    "m-2 xs:m-0 relative border-transparent border-2 hover:border-dashed hover:border-gray-100 ",
  language_div:
    "flex justify-between items-center border-2  md:w-full hover:cursor-move border-2 border-transparent hover:border-dashed hover:border-gray-500 ",
  language_h1:
    "flex text-[14px] xs:text-[12px] md:text-xs font-bold leading-8 hover:shadow-md hover:cursor-text hover:bg-gray-100",
  language_h2_1:
    "flex flex-wrap gap-1 text-[10px] font-semibold leading-relaxed hover:cursor-default",
  language_date: "hover:shadow-md hover:bg-gray-100",
  span1: "span1",
  span2: "span2",
};
export const template_16_styles = {
  full_Name_Style:
    "text-4xl font-bold text-center border-2 border-transparent w-fit xs:text-2xl md:text-4xl hover:shadow-md hover:bg-gray-100 hover:border-dashed hover:border-gray-500",
  jobTitle:
    "text-xl w-fit xs:text-[16px] md:text-xl text-center hover:shadow-md mt-2 hover:bg-gray-100 border-2 border-transparent hover:border-dashed hover:border-gray-500",
  conatact_heading:
    "flex flex-row items-center gap-2 mb-2 -mr-6 text-base font-semibold uppercase border-2 border-transparent md:-mr-6 md:mt-4 hover:border-dashed hover:border-gray-500 hover:w-full",
  contact_ul:
    "flex flex-col w-full gap-3 pl-0 mb-4 text-xs text-gray-300 break-all",
  contact_li:
    "flex flex-row items-center justify-start gap-3 hover:shadow-md hover:text-black hover:bg-gray-100",
  skill_heading:
    "flex flex-row items-center w-full gap-2 my-1 text-base font-semibold text-white uppercase border-2 border-transparent rounded-sm hover:border-dashed hover:border-gray-500",
  skill_ul:
    "flex flex-col w-full gap-2 px-4 mb-4 text-xs text-gray-300 border-2 border-transparent hover:border-dashed hover:border-gray-500",
  skill_li:
    "hover:shadow-md hover:cursor-move parent hover:text-black hover:border-dashed hover:border-gray-500 hover:border  hover:bg-gray-100 border-transparent border-[1px]",
  training_h3: "publication_h3",
  training_div: "publication_div",
  training_h1: "achievement_h1",
  training_h2: "publication_h2",
  training_h2_1: "publication_h2_1",
  training_date: "publication_date",
  training_ul: "publication_ul",
  training_li: "publication_li",
  training_line: "publication_line",
  training_delete1: "publication_delete1",
  training_delete: "publication_delete",
  training_div_input: "publication_div_input",
  training_new_input: "publication_new_input",
  certification_h3: "publication_h3",
  certification_div: "publication_div",
  certification_h1: "achievement_h1",
  certification_h2_1: "publication_h2_1",
  certification_date: "publication_date",
  certification_ul: "publication_ul",
  certification_li: "publication_li",
  certification_line: "publication_line",
  certification_delete1: "publication_delete1",
  certification_delete: "publication_delete",
  certification_div_input: "publication_div_input",
  certification_new_input: "publication_new_input",
  experienceHeading_temp_2: "experienceHeading_temp_2",
  summary_heading: "summary_heading",
  summary_text: "summary_text",
  publication_h3: "publication_h3 ",
  achievement_div: "achievement_div",
  achievement_h2: "achievement_h2",
  achievement_h1: "achievement_h1",
  achievement_save_btn: "achievement-save-btn",
  achievement_delete_btn: "achievement-delete-btn",
  education_h3: "education_h3",
  education_ul: "grid grid-cols-2 gap-2 xs:grid-cols-2 md:grid-cols-2 mt-4",
  education_div: "education_div mt-4 bg-gray-200 rounded-md",
  education_li: "education_li",
  education_delete: "education_delete",
  education_li_2: "education_li_2",
  education_li_italic: "education_li_italic",
  education_li_date: "education_li_date",
  publication_div: "publication_div",
  publication_h2: "publication_h2",
  publication_h2_1: "publication_h2_1",
  publication_new_input: "publication_new_input",
  publication_delete: "publication_delete",
  publication_delete1: "publication_delete1 ",
  publication_line: "publication_line",
  publication_date: "publication_date",
  publication_ul: "publication_ul",
  publication_li: "publication_li",
  publication_div_input: "publication_div_input",
  project_h3: "publication_h3",
  project_div: "publication_div",
  project_h2: "publication_h2",
  project_h2_1: "publication_h2_1",
  project_new_input: "publication_new_input",
  project_delete: "publication_delete",
  project_delete1: "publication_delete1 ",
  project_line: "publication_line",
  project_date: "publication_date",
  project_ul: "publication_ul",
  project_li: "publication_li",
  project_div_input: "publication_div_input",
  interest_h3:
    "flex uppercase text-base xs:px-2 font-semibold text-gray-100 gap-2 items-center  py-1 rounded-sm  border-2 border-transparent hover:border-dashed hover:border-gray-500",
  interest_div:
    "flex justify-between items-center border-2 border-transparent md:w-full hover:cursor-move border-2 border-transparent hover:border-dashed hover:border-gray-500",
  interest_h1:
    "flex text-base font-bold leading-8 hover:shadow-md hover:cursor-text hover:bg-gray-500",
  interest_h2:
    "text-xs xs:text-[12px] md:text-xs font-bold leading-8 hover:shadow-md hover:cursor-text hover:bg-gray-500",
  interest_h2_1:
    "flex flex-wrap gap-1 text-[10px] font-semibold leading-relaxed hover:cursor-default text-gray-100",
  interest_date: "hover:shadow-md hover:bg-gray-500",
  interest_ul: "flex flex-col flex-wrap pl-0 text-xs xs:text-[12px] md:text-xs",
  interest_li:
    "m-2 xs:m-0 relative  hover:border-2 hover:border-dashed  text-gray-100",
  interest_line: "publication_line",
  interest_delete1:
    "hover:border-dashed list-disc hover:cursor-move  hover:bg-gray-500  text-gray-100 parent",
  interest_delete: "publication_delete hidden",
  interest_div_input: "publication_div_input",
  interest_new_input: "publication_new_input",
  award_h3: "publication_h3",
  award_div: "publication_div",
  award_h1: "achievement_h1",
  award_h2: "publication_h2",
  award_h2_1: "publication_h2_1",
  award_date: "publication_date",
  award_ul: "publication_ul",
  award_li: "publication_li",
  award_line: "publication_line",
  award_delete1: "publication_delete1",
  award_delete: "publication_delete",
  award_div_input: "publication_div_input",
  award_new_input: "publication_new_input",
  reference_h3: "publication_h3",
  reference_ul: "reference_ul gap-3 mt-4",
  reference_li: "reference_li bg-gray-200 rounded-md",
  reference_div: "p-2",
  reference_h1: "achievement_h1",
  reference_h2: "publication_h2",
  reference_h2_1: "publication_h2_1",
  reference_date: "publication_date",
  reference_line: "publication_line",
  reference_delete1: "publication_delete1",
  reference_delete: "publication_delete",
  reference_div_input: "publication_div_input",
  reference_new_input: "publication_new_input",
  language_ul: "flex flex-col flex-wrap pl-0 ",
  language_h3:
    "flex uppercase text-base xs:px-2 font-semibold text-gray-100 gap-2 items-center  py-1 rounded-sm  border-2 border-transparent hover:border-dashed hover:border-gray-500",
  language_li:
    "m-2 xs:m-0 relative border-transparent border-2 hover:border-dashed hover:border-gray-100 text-gray-100",
  language_div:
    "flex justify-between items-center border-2 border-transparent md:w-full hover:cursor-move ",
  language_h1:
    "flex text-[14px] xs:text-[12px] md:text-xs font-bold leading-8 hover:shadow-md hover:cursor-text hover:bg-gray-500",
  language_h2_1:
    "flex flex-wrap gap-1 text-[10px] font-semibold leading-relaxed hover:cursor-default",
  language_date: "hover:shadow-md hover:bg-gray-500",
  span1: "span1",
  span2: "span2",
};
export const template_20_styles = {
  full_Name_Style:
    "text-4xl font-bold border-2 border-transparent xs:text-2xl md:4xl lg:text-4xl hover:shadow-md hover:bg-gray-100 hover:border-dashed hover:border-gray-500 ",
  jobTitle:
    "text-lg border-2 border-transparent xs:text-xs md:text-xl  hover:shadow-md hover:bg-gray-100 hover:border-dashed hover:border-gray-500 ",
  conatact_heading:
    "flex flex-row items-center gap-2 mb-2 -mr-6 text-base font-semibold uppercase border-2 border-transparent md:-mr-6 md:mt-4 hover:border-dashed hover:border-gray-500 hover:w-full",
  contact_ul:
    "flex xs:flex-col md:flex-row justify-between w-full gap-3 pl-0 mt-8 mb-4 text-xs break-all mb-6",
  contact_li:
    "flex flex-row items-start justify-start gap-1 hover:shadow-md hover:bg-gray-100",
  skill_heading:
    "flex items-center my-1 justify-center gap-2  text-base font-semibold uppercase wl-full border-2 border-transparent hover:border-dashed hover:border-gray-500 bg-gray-200",
  skill_ul:
    "border-2 border-transparent hover:border-dashed hover:border-gray-500  px-4 flex  flex-wrap gap-1 h-[20%] gap-4 mx-2 text-xs mt-4",
  skill_li:
    "hover:shadow-md w-[30%] xs:w-[45%] xs:pr-4 md:w-[30%] hover:cursor-move parent hover:border-dashed hover:border-gray-500 hover:border  hover:bg-gray-100 border-transparent border-[1px]",
  training_h3: "publication_h3 bg-gray-200",
  training_div: "publication_div",
  training_h1: "achievement_h1",
  training_h2: "publication_h2",
  training_h2_1: "publication_h2_1",
  training_date: "publication_date",
  training_ul: "publication_ul",
  training_li: "publication_li",
  training_line: "publication_line",
  training_delete1: "publication_delete1",
  training_delete: "publication_delete",
  training_div_input: "publication_div_input",
  training_new_input: "publication_new_input",
  certification_h3: "publication_h3",
  certification_div: "publication_div",
  certification_h1: "achievement_h1",
  certification_h2_1: "publication_h2_1",
  certification_date: "publication_date",
  certification_ul: "publication_ul",
  certification_li: "publication_li",
  certification_line: "publication_line",
  certification_delete1: "publication_delete1",
  certification_delete: "publication_delete",
  certification_div_input: "publication_div_input",
  certification_new_input: "publication_new_input",
  experienceHeading_temp_2: "experienceHeading_temp_2 bg-gray-200",
  summary_heading: "summary_heading",
  summary_text: "summary_text",
  publication_h3: "publication_h3 bg-gray-200",
  achievement_div: "achievement_div",
  achievement_h2: "achievement_h2",
  achievement_h1: "achievement_h1 mt-4",
  achievement_save_btn: "achievement-save-btn",
  achievement_delete_btn: "achievement-delete-btn",
  education_h3: "education_h3 bg-gray-200",
  education_ul: "education_ul mt-4",
  education_div: "education_div",
  education_li: "education_li",
  education_delete: "education_delete",
  education_li_2: "education_li_2",
  education_li_italic: "education_li_italic",
  education_li_date: "education_li_date",
  publication_div: "publication_div",
  publication_h2: "publication_h2",
  publication_h2_1: "publication_h2_1",
  publication_new_input: "publication_new_input",
  publication_delete: "publication_delete",
  publication_delete1: "publication_delete1 ",
  publication_line: "publication_line",
  publication_date: "publication_date",
  publication_ul: "publication_ul",
  publication_li: "publication_li",
  publication_div_input: "publication_div_input",
  project_h3: "publication_h3 bg-gray-200",
  project_div: "publication_div",
  project_h2: "publication_h2",
  project_h2_1: "publication_h2_1",
  project_new_input: "publication_new_input",
  project_delete: "publication_delete",
  project_delete1: "publication_delete1 ",
  project_line: "publication_line",
  project_date: "publication_date",
  project_ul: "publication_ul",
  project_li: "publication_li",
  project_div_input: "publication_div_input",
  interest_h3: "publication_h3 bg-gray-200",
  interest_div: "publication_div",
  interest_h1: "achievement_h1",
  interest_h2: "publication_h2",
  interest_h2_1: "publication_h2_1",
  interest_date: "publication_date",
  interest_ul: "publication_ul",
  interest_li: "publication_li",
  interest_line: "publication_line",
  interest_delete1: "publication_delete1 parent",
  interest_delete: "publication_delete hidden",
  interest_div_input: "publication_div_input",
  interest_new_input: "publication_new_input",
  award_h3: "publication_h3 bg-gray-200",
  award_div: "publication_div",
  award_h1: "achievement_h1",
  award_h2: "publication_h2",
  award_h2_1: "publication_h2_1",
  award_date: "publication_date",
  award_ul: "publication_ul",
  award_li: "publication_li",
  award_line: "publication_line",
  award_delete1: "publication_delete1",
  award_delete: "publication_delete",
  award_div_input: "publication_div_input",
  award_new_input: "publication_new_input",
  reference_h3: "publication_h3 bg-gray-200",
  reference_ul: "reference_ul",
  reference_li: "reference_li",
  reference_div: "p-2",
  reference_h1: "achievement_h1",
  reference_h2: "publication_h2",
  reference_h2_1: "publication_h2_1",
  reference_date: "publication_date",
  reference_line: "publication_line",
  reference_delete1: "publication_delete1",
  reference_delete: "publication_delete",
  reference_div_input: "publication_div_input",
  reference_new_input: "publication_new_input",
  language_h3: "publication_h3 bg-gray-200",
  language_ul: "reference_ul",
  language_li: "reference_li",
  language_div: "language_div ",
  language_h1: "achievement_h1",
  language_h2_1: "publication_h2_1",
  language_date: "publication_date",
  span1: "span1",
  span2: "span2",
};

export const customStyle_4 = {
  borderTopBottom: false,
  borderBottom: true,
  centeredHeading: false,
};
export const customStyle_2 = {
  borderTopBottom: false,
  borderBottom: false,
  centeredHeading: false,
};
export const customStyle_8 = { borderTopBottom: true, centeredHeading: true };
export const customStyle_6 = { borderTopBottom: true, centeredHeading: false };
export const customStyle_9 = {
  borderTopBottom: true,
  centeredHeading: false,
  education_bg: "education_bg",
};
export const customStyle_10 = {
  borderTopBottom: false,
  centeredHeading: false,
  bgColor: "bg_color_9",
  education_bg: "education_bg",
};
export const customStyle_15 = {
  borderTopBottom: false,
  centeredHeading: false,
  bgColor: "bg_color",
  education_bg: "education_bg",
};
export const customStyle_16 = {
  borderTopBottom: false,
  centeredHeading: false,
  borderBottom: true,
  education_bg: "education_bg",
};
export const customStyle_20 = {
  // hideIcons: true,
  borderTopBottom: false,
  borderBottom: true,
  centeredHeading: true,
  bgColor: "bg-gray-200",
};
