import "../polyfills";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import ReduxProvider from "./ReduxProvider.jsx";
import UserDataProvider from "./UserDataProvider";
import { TourContextProvider } from "@/context/TourContext";
import { AppContextsProvider } from "@/context/AppContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const geistMono = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <TourContextProvider> 
            <AppContextsProvider>
        <ReduxProvider>
          <Providers>
          <UserDataProvider />
            {children}</Providers>
        </ReduxProvider>
         </AppContextsProvider>
         </TourContextProvider>
      </body>
    </html>
  );
}
